<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rifa - Números Disponibles</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            min-height: 100vh;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 100%;
        }
        h1 {
            text-align: center;
            color: #333;
        }
        form {
            display: flex;
            flex-direction: column;
            margin-bottom: 20px;
        }
        input[type="text"], input[type="email"], select {
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        button {
            padding: 10px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 10px;
        }
        button:hover {
            background-color: #218838;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }
        th {
            background-color: #4CAF50;
            color: white;
        }
        .taken {
            background-color: #f44336;
            color: white;
        }
        .available {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1>Participa en la Rifa</h1>
        <form id="rifaForm" action="#" method="post" onsubmit="return verificarFormulario()">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required>

            <label for="email">Correo Electrónico:</label>
            <input type="email" id="email" name="email" required>

            <label for="numero">Selecciona tu número:</label>
            <select id="numero" name="numero" required>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
            </select>

            <button type="submit">Participar</button>
        </form>

        <h2>Números Disponibles</h2>
        <table>
            <thead>
                <tr>
                    <th>Número</th>
                    <th>Estado</th>
                </tr>
            </thead>
            <tbody id="tablaNumeros">
                <tr>
                    <td>1</td>
                    <td class="taken">Tomado</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td class="available">Disponible</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td class="taken">Tomado</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td class="available">Disponible</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td class="available">Disponible</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td class="taken">Tomado</td>
                </tr>
            </tbody>
        </table>
    </div>

    <script>
        // Simulamos los números tomados
        const numerosTomados = [1, 3, 6]; // Puedes actualizar este array según sea necesario

        // Función para verificar el formulario antes de enviar
        function verificarFormulario() {
            const nombre = document.getElementById("nombre").value;
            const email = document.getElementById("email").value;
            const numeroSeleccionado = parseInt(document.getElementById("numero").value);

            // Verificación del correo
            if (!validarEmail(email)) {
                alert("Por favor ingresa un correo electrónico válido.");
                return false;
            }

            // Verificar si el número ya está tomado
            if (numerosTomados.includes(numeroSeleccionado)) {
                alert("El número seleccionado ya está tomado. Por favor elige otro.");
                return false;
            }

            alert("Formulario enviado correctamente. ¡Gracias por participar!");
            return true;
        }

        // Función para validar el formato del correo electrónico
        function validarEmail(email) {
            const regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
            return regex.test(email);
        }
    </script>

</body>
</html>

